
@host = http://localhost:4004
@tenant ={{host}}/scoreboard
@name = JohnEBGone

@scores = {{tenant}}/HighScore
@highScore = {{tenant}}/HighScore?$orderby=score desc&$top=10&$skip=0
@weeklyHighScore = {{tenant}}/HighScore?$orderby=score desc&$filter=created gt 2023-02-12T00:00:00.000Z&$top=10
@ranking = {{tenant}}/Ranking?name={{name}}
@healthCheck = {{host}}/health

### 1. Get High Score Descending
# @name getHighScoreReq
GET {{highScore}}
Accept: application/json
Content-Type: application/json

### 2. Get Weekly High Score for this week
# @name getWeeklyHighScoreReq
GET {{weeklyHighScore}}
Accept: application/json
Content-Type: application/json

### 3. Get Ranking for given name
# @name getRankingReq
GET {{ranking}}
Accept: application/json
Content-Type: application/json

### 4. Post score
# @name getRankingReq
POST {{scores}}
Accept: application/json
Content-Type: application/json

{
    "name": "Jake",
    "score": 100
}

### Simple Health Check (not OData)
# @name healthCheckReq
GET {{healthCheck}}
Content-Type: application/json